changelog:
  categories:
    - title: 🎉 Features
      labels:
        - feature
    - title: ✨ Refinements
      labels:
        - refinement
    - title: 🏠 Maintenances
      labels:
        - maintenance
    - title: 🐛 Bug Fixes
      labels:
        - Bug
    - title: 🔥 Removes
      labels:
        - remove
    - title: Other Changes
      labels:
        - "*"
